import React, { useEffect } from 'react';
import { Modal, Form, Input, Typography } from 'antd';

const { Text } = Typography;

const MachineTypeModal = ({ visible, onCancel, onSubmit, machineType }) => {
  const [form] = Form.useForm();
  const isEditing = !!machineType;
  
  // Reset form when modal opens/closes or machineType changes
  useEffect(() => {
    if (visible) {
      form.resetFields();
      
      if (machineType) {
        // Fill form with machine type data for editing
        form.setFieldsValue({
          name: machineType.name,
        });
      }
    }
  }, [visible, machineType, form]);
  
  const handleSubmit = () => {
    form.validateFields()
      .then(values => {
        onSubmit(values);
        form.resetFields();
      })
      .catch(info => {
        console.log('Validate Failed:', info);
      });
  };

  return (
    <Modal
      title={isEditing ? "Update Machine Type" : "Add New Machine Type"}
      open={visible}
      onCancel={onCancel}
      onOk={handleSubmit}
      okText={isEditing ? "Update" : "Add"}
      cancelText="Cancel"
    >
      <Form
        form={form}
        layout="vertical"
        name="machine_type_form"
      >
        {isEditing && (
          <Form.Item label="Machine Type ID">
            <Input value={machineType?.machine_type_id} disabled style={{ color: '#666' }} />
            <Text type="secondary" style={{ fontSize: '12px' }}>
              Machine Type ID cannot be modified
            </Text>
          </Form.Item>
        )}
        
        <Form.Item
          name="name"
          label="Machine Type Name"
          rules={[
            { required: true, message: 'Please enter machine type name!' },
            { min: 2, message: 'Name must be at least 2 characters long!' },
            { max: 100, message: 'Name cannot exceed 100 characters!' },
          ]}
        >
          <Input placeholder="Enter machine type name" />
        </Form.Item>
      </Form>
      
      {!isEditing && (
        <Text type="secondary">
          Note: Machine Type ID will be auto-generated by the system
        </Text>
      )}
    </Modal>
  );
};

export default MachineTypeModal; 